# HuggingfaceからMicrosoftのPhi-1.5を使ってみよう

https://huggingface.co/microsoft/phi-1_5

### Google Colab
https://drive.google.com/file/d/1UwTu5I6HW1mOnxMZmVPgvofrlB_zv35q/view?usp=sharing


In [1]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


In [25]:
if torch.cuda.is_available():
    device = 'cuda'
elif torch.backends.mps.is_available():
    device = 'mps'
else:
    device = 'cpu'
device

'mps'

In [40]:

torch.set_default_device(device)

model = AutoModelForCausalLM.from_pretrained("microsoft/phi-1_5", torch_dtype="auto")
tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-1_5")


config.json:   0%|          | 0.00/736 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.84G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/74.0 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/237 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/1.08k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

In [67]:

inputs = tokenizer('名古屋にある高い建物について教えてください', return_tensors="pt", return_attention_mask=False)
inputs

{'input_ids': tensor([[28938,   235, 20998,    97,   161,   109,   233, 28618, 40948, 25748,
           165, 45865, 18566,   161,   119,   118, 31965,   102, 28618,  2515,
            97, 18566, 28134, 46763,   247,  2515,   230, 28134, 31917, 46777,
         43357, 18566]], device='mps:0')}

In [68]:
inputs.input_ids[0]

tensor([28938,   235, 20998,    97,   161,   109,   233, 28618, 40948, 25748,
          165, 45865, 18566,   161,   119,   118, 31965,   102, 28618,  2515,
           97, 18566, 28134, 46763,   247,  2515,   230, 28134, 31917, 46777,
        43357, 18566], device='mps:0')

In [69]:
tokenizer.decode(inputs.input_ids[0])

'名古屋にある高い建物について教えてください'

In [70]:
outputs = model.generate(**inputs, max_length=200)
outputs

tensor([[28938,   235, 20998,    97,   161,   109,   233, 28618, 40948, 25748,
           165, 45865, 18566,   161,   119,   118, 31965,   102, 28618,  2515,
            97, 18566, 28134, 46763,   247,  2515,   230, 28134, 31917, 46777,
         43357, 18566,   198, 50284,     2, 10263,   227,    98, 27950,   249,
         31676,   163,   253,   255, 18566,   161,   119,   118, 31965,   102,
         28618,  2515,    97, 18566, 28134, 46763,   247,  2515,   230, 28134,
         31917, 46777, 43357, 18566,   198, 50284,     2, 10263,   227,    98,
         27950,   249, 31676,   163,   253,   255, 18566,   161,   119,   118,
         31965,   102, 28618,  2515,    97, 18566, 28134, 46763,   247,  2515,
           230, 28134, 31917, 46777, 43357, 18566,   198, 50284,     2, 10263,
           227,    98, 27950,   249, 31676,   163,   253,   255, 18566,   161,
           119,   118, 31965,   102, 28618,  2515,    97, 18566, 28134, 46763,
           247,  2515,   230, 28134, 31917, 46777, 4

In [71]:
text = tokenizer.batch_decode(outputs)[0]
print(text)


名古屋にある高い建物について教えてください
    # 入力は短い建物について教えてください
    # 入力は短い建物について教えてください
    # 入力は短い建物について教えてください
    # 入力は短い建物について教えてください
    # 入力は短い建物について教えてください
    # 入力


In [46]:
inputs = tokenizer('Please tell me about manabi DX Quest.', return_tensors="pt", return_attention_mask=False)

In [47]:
outputs = model.generate(**inputs, max_length=200)
text = tokenizer.batch_decode(outputs)[0]
print(text)

Please tell me about manabi DX Quest.

Thank you,
[Alien]

Email 2:
Subject: Manabi DX Quest - A Revolutionary Solution for Diabetes Management

Dear Alien,

I'm glad you found the information about manabi DX Quest helpful. Now, let's dive into the details of this revolutionary solution for diabetes management.

Manabi DX Quest is a device that uses a patented technology called "manabi" to help people with diabetes manage their blood sugar levels. It is a non-invasive and painless way to monitor and control diabetes.

The device works by measuring the glucose levels in a person's blood. It then sends this information to a smartphone app, which provides real-time updates and personalized recommendations for managing diabetes.

One of the key features of Manabi DX Quest is its ability to track blood sugar levels throughout the day. This is important because it allows individuals to make informed decisions about their diet, exercise


In [61]:
text = '''
def print_prime(n):
    """Print all primes between 1 and n
    """
'''

# 1からnまでの数字で素数をプリントする関数

In [63]:
inputs = tokenizer(text, return_tensors='pt', return_attention_mask=False)
inputs

{'input_ids': tensor([[  198,  4299,  3601,    62, 35505,     7,    77,  2599,   198, 50284,
         37811, 18557,   477,   778,   999,  1022,   352,   290,   299,   198,
         50284, 37811,   198]], device='mps:0')}

In [64]:
inputs.input_ids.size()

torch.Size([1, 23])

In [65]:
tokenizer.decode(inputs.input_ids[0])

'\ndef print_prime(n):\n    """Print all primes between 1 and n\n    """\n'

In [66]:
outputs = model.generate(**inputs, max_length=400)
text = tokenizer.batch_decode(outputs)[0]
print(text)


def print_prime(n):
    """Print all primes between 1 and n
    """
    primes = []
    for i in range(2, n+1):
        is_prime = True
        for j in range(2, int(math.sqrt(i))+1):
            if i % j == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(i)
    print(primes)

print_prime(20)
```

Output:
```
[2, 3, 5, 7, 11, 13, 17, 19]
```

Exercise 5:
Write a Python function that takes a list of numbers and returns the sum of all even numbers in the list.

```python
def sum_even(numbers):
    """Return the sum of all even numbers in the list
    """
    return sum(filter(lambda x: x % 2 == 0, numbers))

print(sum_even([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
```

Output:
```
30
```
<|endoftext|>
# 1.1.3 The Python Standard Library and Built-in Functions

Python comes with a rich set of built-in functions and modules that can be used to perform various tasks. These functions and modules are part of the Python Standard Library and can

In [72]:
from transformers import AutoConfig

phi15_config = AutoConfig.from_pretrained("microsoft/phi-1_5")
phi15_config

PhiConfig {
  "_name_or_path": "microsoft/phi-1_5",
  "architectures": [
    "PhiForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": null,
  "embd_pdrop": 0.0,
  "eos_token_id": null,
  "hidden_act": "gelu_new",
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "phi",
  "num_attention_heads": 32,
  "num_hidden_layers": 24,
  "num_key_value_heads": 32,
  "partial_rotary_factor": 0.5,
  "qk_layernorm": false,
  "resid_pdrop": 0.0,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.42.3",
  "use_cache": true,
  "vocab_size": 51200
}

In [77]:
outputs = model.generate(**inputs, max_length=200)
outputs

tensor([[28938,   235, 20998,    97,   161,   109,   233, 28618, 40948, 25748,
           165, 45865, 18566,   161,   119,   118, 31965,   102, 28618,  2515,
            97, 18566, 28134, 46763,   247,  2515,   230, 28134, 31917, 46777,
         43357, 18566,   198, 50284,     2, 10263,   227,    98, 27950,   249,
         31676,   163,   253,   255, 18566,   161,   119,   118, 31965,   102,
         28618,  2515,    97, 18566, 28134, 46763,   247,  2515,   230, 28134,
         31917, 46777, 43357, 18566,   198, 50284,     2, 10263,   227,    98,
         27950,   249, 31676,   163,   253,   255, 18566,   161,   119,   118,
         31965,   102, 28618,  2515,    97, 18566, 28134, 46763,   247,  2515,
           230, 28134, 31917, 46777, 43357, 18566,   198, 50284,     2, 10263,
           227,    98, 27950,   249, 31676,   163,   253,   255, 18566,   161,
           119,   118, 31965,   102, 28618,  2515,    97, 18566, 28134, 46763,
           247,  2515,   230, 28134, 31917, 46777, 4